//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_Egurnova_02_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Egurnova_YP01Entities : DbContext
    {
        private static Egurnova_YP01Entities _context;
        public Egurnova_YP01Entities()
            : base("name=Egurnova_YP01Entities")
        {
        }

        public static Egurnova_YP01Entities GetContext()
        {
            if (_context == null)
                _context = new Egurnova_YP01Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<FaultType> FaultType { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StatusType> StatusType { get; set; }
        public virtual DbSet<Technicians> Technicians { get; set; }
    }
}
