//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_Egurnova_02_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public Nullable<System.DateTime> RequestDateSub { get; set; }
        public Nullable<System.DateTime> RequestDateEnd { get; set; }
        public Nullable<System.DateTime> PeriodExecution { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> FaultTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> TechniciansID { get; set; }
        public string Comment { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual FaultType FaultType { get; set; }
        public virtual Technicians Technicians { get; set; }
        public virtual StatusType StatusType { get; set; }
    }
}
